all: bcols base comparisons segment utils

.PHONY: bcols base comparisons segment utils

bcols:
	go generate bcols.go
base:
	go generate base.go
segment:
	go generate segment.go
utils:
	go generate utils.go
comparisons:
	go generate comparisons.go
