all: bcols base comparisons segment utils convert regroup dechunk replace

.PHONY: bcols base comparisons segment utils convert regroup dechunk replace

bcols:
	go generate bcols.go
base:
	go generate base.go
segment:
	go generate segment.go
utils:
	go generate utils.go
comparisons:
	go generate comparisons.go
convert:
	go generate convert.go
regroup:
	go generate regroup.go
dechunk:
	go generate dechunk.go
replace:
	go generate replace.go
