all: bcols base comparisons segment utils convert

.PHONY: bcols base comparisons segment utils convert

bcols:
	go generate bcols.go
base:
	go generate base.go
segment:
	go generate segment.go
utils:
	go generate utils.go
comparisons:
	go generate comparisons.go
convert:
	go generate convert.go
